# This is a Docker Compose file for setting up the morphic-stack environment.

name: morphic-stack
services:
  morphic:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile
    command: bun dev # Use `bun dev -H 0.0.0.0` to listen on all interfaces
    env_file: .env.local # Load environment variables
    ports:
      - '3000:3000' # Maps port 3000 on the host to port 3000 in the container.
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    env_file: .env.local # can remove if you want to use env variables or in settings.yml
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data

volumes:
  redis_data:
  searxng_data:
